# Permalinks
permalink:        pretty

# Setup

title:            Kristina & Immo are getting married!
partner1:         Kristina
partner2:         Immo
wedding-year:     2026
wedding-month:    8
wedding-day:      22
wedding-hour:     16
wedding-tag:      August 22th, 2026 Leavenworth, Washington
wedding-location: Blue Elk Inn, Leavenworth, WA
copyright:        Immo Landwerth & Kristina Walker
rsvp-link:        https://www.zola.com/wedding/kristinaandimmo/rsvp
